# 1. Create a 3x3x3 array with random values

In [2]:
import numpy as np
a=np.empty((3,3,3))#creates an random  array of order 3X3X3
print("The Array is-")
print(a)
print("The Shape of Array is-")
print(a.shape)

The Array is-
[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.95820760e-306 3.22643519e-307 7.56599807e-307]
  [8.90104239e-307 3.33776697e-307 9.79054228e-307]]

 [[9.34598926e-307 9.34583987e-307 1.37961505e-306]
  [1.60219035e-306 8.01097889e-307 1.78020169e-306]
  [7.56601165e-307 1.02359984e-306 1.33510679e-306]]

 [[2.22522597e-306 1.24611674e-306 1.29061821e-306]
  [6.23057349e-307 1.29062025e-306 6.89807188e-307]
  [2.22522596e-306 1.42404727e-306 1.11253693e-308]]]
The Shape of Array is-
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
b=np.zeros((5,5))#creates a zeros matrix of specified order
print("Initial Matrix-")
print(b)
for i in range(len(b)):
    for j in range(len(b)):
        if(i==j+1):
            b[i][j]=i
print("Final Matrix-")
print(b)

Initial Matrix-
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Final Matrix-
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
c=np.zeros((8,8))#creates a zeros matrix of specified order 
print("Initial Matrix-")
print(c)
for i in range(len(c)):
    for j in range(len(c)):
        if(j%2!=0):
            c[i][j]=255
print("Final Matrix-")
print(c)

Initial Matrix-
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Final Matrix-
[[  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]
 [  0. 255.   0. 255.   0. 255.   0. 255.]]


# 4. Normalize a 5x5 random matrix

In [5]:
d=np.random.randn(5,5)#creates a matrix of specified filled with random numbers
print("The random matrix is-")
print(d)
normal=np.linalg.norm(d)#computes the norm of the given matrix 
print("The norm value of random matrix is-")
print(normal)
e=np.divide(d,normal)#computes the normalized matrix
print("The normalized random mattrix is-")
print(e)

The random matrix is-
[[ 0.48235768 -0.51616765  1.16486502  0.47109256  0.29672747]
 [ 0.49010497  0.48793111  0.27100201 -2.17798913  0.55462808]
 [-1.36968638  1.12279948 -0.60047261  0.71678265  0.01728035]
 [-0.91196371 -0.18368924 -1.26115028 -0.06433866 -0.5665748 ]
 [ 0.51347817  1.46499638  0.28413164  1.07447794  1.57387749]]
The norm value of random matrix is-
4.547920580812293
The normalized random mattrix is-
[[ 0.10606115 -0.11349531  0.25613135  0.10358417  0.06524465]
 [ 0.10776463  0.10728664  0.05958811 -0.47889779  0.12195201]
 [-0.30116761  0.24688195 -0.13203234  0.15760668  0.00379962]
 [-0.20052323 -0.04038972 -0.27730262 -0.01414683 -0.12457887]
 [ 0.11290394  0.32212444  0.06247507  0.23625697  0.3460653 ]]


# 5. How to find common values between two arrays?

In [6]:
f=np.array([1,2,3,4,5])
print("The 1st array is-")
print(f)
g=np.array([2,4,6,8,10])
print("The 2nd array is-")
print(g)
com_values=np.intersect1d(f,g)#computes common values in two input arrays
print("Common values between two arrays are-")
print(com_values)

The 1st array is-
[1 2 3 4 5]
The 2nd array is-
[ 2  4  6  8 10]
Common values between two arrays are-
[2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday =np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ",yesterday)
today= np.datetime64('today', 'D')
print("Today's Date: ",today)
tomorrow= np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-25
Today's Date:  2020-07-26
Tomorrow's Date:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [8]:
h=np.array([1,2,3])
i=np.array([1,2,3])
comparison = h == i
equal_arrays = comparison.all()#compare two arrays and returns boolean expression
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
print("Output:",equal_arrays)

Output is True if two arrays are equal
Output is False if two arrays are equal
Output: True


In [9]:
h=np.array([1,2,3])
i=np.array([4,5,6])
comparison = h == i
equal_arrays = comparison.all()
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
print("Output:",equal_arrays)

Output is True if two arrays are equal
Output is False if two arrays are equal
Output: False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [10]:
vec=np.random.randn(10,1)#creates a random vector of given order
print("The random vector is-")
print(vec)
max_val=np.amax(vec)#computes the maximum value from a given vector
print("The maximum value in the vector is-")
print(max_val)
loc=np.where(vec==max_val)#find the index of the maximum value
vec[loc]=0
print("The new vector is-")
print(vec)

The random vector is-
[[-0.03413999]
 [ 0.7951733 ]
 [-1.4477217 ]
 [ 0.69673216]
 [ 1.36107518]
 [ 1.07660192]
 [ 1.02453404]
 [-0.25168064]
 [ 0.57316233]
 [ 0.27620562]]
The maximum value in the vector is-
1.3610751824207612
The new vector is-
[[-0.03413999]
 [ 0.7951733 ]
 [-1.4477217 ]
 [ 0.69673216]
 [ 0.        ]
 [ 1.07660192]
 [ 1.02453404]
 [-0.25168064]
 [ 0.57316233]
 [ 0.27620562]]


# 9. How to print all the values of an array?

In [11]:
l=np.random.randn(3,)#creates a random array of given order
print("The array is:")
print(l)
for i in range(len(l)):
    print("The element at index(",i,") is:",l[i])

The array is:
[ 0.76508359 -2.29245283  1.35917658]
The element at index( 0 ) is: 0.7650835927247875
The element at index( 1 ) is: -2.2924528272990266
The element at index( 2 ) is: 1.3591765847857575


In [12]:
l=np.random.randn(3,3)#creates a random array of given order
print("The array is:")
print(l)
for i in range(len(l)):
    for j in range(len(l)):
        print("The element at index(",i,",",j,")is:",l[i][j])

The array is:
[[ 0.1246985   0.28299555 -1.90417455]
 [ 0.18755522  0.37933311  1.47890851]
 [ 0.48424163  1.18128457  1.81701323]]
The element at index( 0 , 0 )is: 0.12469849972623377
The element at index( 0 , 1 )is: 0.28299554784375663
The element at index( 0 , 2 )is: -1.9041745465959785
The element at index( 1 , 0 )is: 0.18755521885152385
The element at index( 1 , 1 )is: 0.379333107866843
The element at index( 1 , 2 )is: 1.4789085146508985
The element at index( 2 , 0 )is: 0.4842416273247458
The element at index( 2 , 1 )is: 1.1812845663029183
The element at index( 2 , 2 )is: 1.8170132317470864


# 10.Subtract the mean of each row of a matrix

In [13]:
arr=np.random.randn(3,3)#creates a random matrix of given order
print("The matrix is-")
print(arr)
print("The mean value of each row is-")
arr1=np.mean(arr,axis=1)#computes the mean of each row
print(arr1)
arr2=arr-arr1
print("The matrix after the mean is subtracted-")
print(arr2)

The matrix is-
[[ 0.63240475 -0.3014075   0.91496677]
 [ 0.62132604 -0.90906708 -0.64540132]
 [-0.53588728 -0.2984367   0.07797309]]
The mean value of each row is-
[ 0.41532134 -0.31104745 -0.25211696]
The matrix after the mean is subtracted-
[[ 0.21708341  0.00963996  1.16708373]
 [ 0.2060047  -0.59801962 -0.39328436]
 [-0.95120862  0.01261075  0.33009006]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [14]:
Z = np.random.randn(10,1)#creates a random vector of given order
print("The original vector is:")
print(Z)
I=np.random.randint(0,len(Z),4)#generates 4 random integers in a specified range,used as index values
print("The Index values are:")
print(I)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(Z,I,1)#Adds 1 to the elements in given vector (Z) at the specified index values(I)
print(Z)

The original vector is:
[[ 0.45018474]
 [-1.91367085]
 [-0.41517137]
 [ 0.79518224]
 [-0.2442316 ]
 [ 0.27338978]
 [-0.10248207]
 [ 1.04151811]
 [-1.08820549]
 [-0.54147853]]
The Index values are:
[1 4 1 6]
Final vector after adding 1 to corresponding elements at the specified indices:
[[ 0.45018474]
 [ 0.08632915]
 [-0.41517137]
 [ 0.79518224]
 [ 0.7557684 ]
 [ 0.27338978]
 [ 0.89751793]
 [ 1.04151811]
 [-1.08820549]
 [-0.54147853]]


# 12.How to get the diagonal of a dot product?

In [15]:
u=np.random.randn(3,3)#creates a random matrix of given order
print("The first 3X3 array is- ")
print(u)
v=np.random.randn(3,3)
print("The second 3X3 array is- ")
print(v)
w=np.dot(u,v)#computes the dot product of two given matrices
print("The corresponding dot product is- ")
print(w)
z=np.diag(w)#choose the diagnol elements of given matrix
print("The corresponding diagnol elements are- ")
print(z)

The first 3X3 array is- 
[[ 0.24816917  0.28775726  0.09279286]
 [-0.41982536 -0.52175898  0.57832038]
 [ 0.10846351  1.44884324  0.54897602]]
The second 3X3 array is- 
[[-1.94571187 -0.1856822   0.17207192]
 [-0.91458085  0.24720413  1.8773639 ]
 [ 2.63100469 -1.69779691 -0.07391023]]
The corresponding dot product is- 
[[-0.50190454 -0.13248924  0.5760697 ]
 [ 2.81561359 -1.03289743 -1.09451543]
 [-0.09176453 -0.5940295   2.69809459]]
The corresponding diagnol elements are- 
[-0.50190454 -1.03289743  2.69809459]


# 13.How to find the most frequent value in an array?

In [16]:
k=np.array([1,2,3,3,5,3,6,6,7,6,6,8])
np.argmax(np.bincount(k))#finds the value that is repeated maximum number of times in a given array

6

# 14.How to get the n largest values of an array?

In [19]:
M=np.arange(1000)#generates a sequential array with numbers 0 to 999
np.random.shuffle(M)
n=int(input("Enter the value of n:"))
print("The",n,"largest value of the array are:")
print (M[np.argpartition(-M,n)[:n]])#prints the n largest values in the specified array

Enter the value of n:4
The 4 largest value of the array are:
[999 998 997 996]


# 15.How to create a record array from a regular array?

In [20]:
reg_arr = np.array([["Pranjul", 88.5, 90],["Manjeet", 87, 99],["Abdul", 85.5, 91]])#generates a 2D array
print("Original array:")
print(reg_arr)
print("\nRecord array:")
rec_arr = np.core.records.fromarrays(reg_arr.T,names='col1, col2, col3',formats = 'S80, f8, i8')# generates a reccord array
print(rec_arr)
type(rec_arr)

Original array:
[['Pranjul' '88.5' '90']
 ['Manjeet' '87' '99']
 ['Abdul' '85.5' '91']]

Record array:
[(b'Pranjul', 88.5, 90) (b'Manjeet', 87. , 99) (b'Abdul', 85.5, 91)]


numpy.recarray